import { useEffect } from 'preact/hooks';

type JsPdfDocument = {
  internal: { pageSize: { getWidth: () => number; getHeight: () => number } };
  setFillColor: (...args: number[]) => void;
  rect: (x: number, y: number, width: number, height: number, style?: string) => void;
  roundedRect: (x: number, y: number, width: number, height: number, rx: number, ry: number, style?: string) => void;
  setTextColor: (...args: number[]) => void;
  setFontSize: (size: number) => void;
  setFont: (family: string, style?: string) => void;
  text: (text: string, x: number, y: number) => void;
  addPage: (orientation?: string) => void;
  addImage: (image: string, type: string, x: number, y: number, width: number, height: number) => void;
  save: (filename: string) => void;
};

type ChartSection = {
  button: string;
  name: string;
  subButton?: string;
  afterClick?: () => void;
};

function text(id: string, fallback = 'N/A') {
  return (document.getElementById(id)?.textContent || fallback).trim() || fallback;
}

function click(selector: string) {
  document.querySelector<HTMLElement>(selector)?.click();
}

function isVisible(el: HTMLElement) {
  const style = window.getComputedStyle(el);
  return style.display !== 'none' && style.visibility !== 'hidden' && el.getClientRects().length > 0;
}

function captureBgColor() {
  if ((document.documentElement.getAttribute('data-theme') || 'dark') === 'light') return '#ffffff';
  return getComputedStyle(document.documentElement).getPropertyValue('--surface-1').trim() || '#0f1419';
}

function delay(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}

function addFooter(doc: JsPdfDocument, pageWidth: number, pageHeight: number, margin: number, hostname: string, pageNum: number) {
  doc.setFillColor(35, 47, 62);
  doc.rect(0, pageHeight - 10, pageWidth, 10, 'F');
  doc.setTextColor(255, 153, 0);
  doc.setFontSize(7);
  doc.text(`SARkart Performance Report - ${hostname}`, margin, pageHeight - 4);
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum}`, pageWidth - margin - 12, pageHeight - 4);
}

async function captureVisibleCharts() {
  const html2canvas = window.html2canvas;
  if (!html2canvas) return [];

  const containers = ['containerA', 'containerB', 'containerC', 'containerD']
    .map((id) => document.getElementById(id))
    .filter((el): el is HTMLElement => {
      if (!el || !isVisible(el) || !el.innerHTML.trim()) return false;
      return el.classList.contains('js-plotly-plot') || !!el.querySelector('.plot-container.plotly');
    })
    .map((el) => (el.closest('.chart-card') as HTMLElement | null) || el);

  const images = await Promise.all(containers.map(async (container) => {
    try {
      const canvas = await html2canvas(container, {
        backgroundColor: captureBgColor(),
        scale: 2,
        logging: false,
        useCORS: true
      });
      return canvas.toDataURL('image/png');
    } catch (_error) {
      return null;
    }
  }));

  return images.filter((image): image is string => !!image);
}

async function renderSection(section: ChartSection) {
  if (section.afterClick) {
    section.afterClick();
    await delay(700);
    return;
  }

  click(section.button);
  if (section.subButton) {
    await delay(200);
    click(section.subButton);
  }
  await delay(700);
}

async function generatePDFReport() {
  const JsPDF = window.jspdf?.jsPDF;
  if (!JsPDF) {
    console.error('[SARkart] jsPDF is not loaded');
    return;
  }

  const doc: JsPdfDocument = new JsPDF('landscape', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  let hostname = 'Unknown';
  let osInfo = 'Unknown';
  let kernelInfo = '';
  try { hostname = window.getHostname?.() || hostname; } catch (_error) {}
  try { osInfo = window.getOS?.() || osInfo; } catch (_error) {}
  try { kernelInfo = window.getKernel?.() || ''; } catch (_error) {}

  const dateInfo = text('dateFilterInfo', window._allDatesArr?.length ? `${window._allDatesArr.length} days` : '');
  const reportDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  doc.setFillColor(35, 47, 62);
  doc.rect(0, 0, pageWidth, 50, 'F');
  doc.setFillColor(255, 153, 0);
  doc.rect(0, 50, pageWidth, 3, 'F');
  doc.setTextColor(255, 153, 0);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('SAR Performance Report', margin, 32);
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by SARkart', margin, 44);

  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, 62, contentWidth, 45, 3, 3, 'F');
  doc.setTextColor(35, 47, 62);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Server Information', margin + 8, 76);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  doc.text('Hostname:', margin + 8, 86);
  doc.setFont('helvetica', 'bold');
  doc.text(hostname, margin + 45, 86);
  doc.setFont('helvetica', 'normal');
  doc.text('Operating System:', margin + 8, 94);
  doc.setFont('helvetica', 'bold');
  doc.text(osInfo, margin + 55, 94);
  doc.setFont('helvetica', 'normal');
  doc.text('Kernel:', margin + 8, 102);
  doc.setFont('helvetica', 'bold');
  doc.text(kernelInfo, margin + 45, 102);

  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, 115, contentWidth, 35, 3, 3, 'F');
  doc.setTextColor(35, 47, 62);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Peak Summary', margin + 8, 129);

  const colW = contentWidth / 3;
  [
    { label: 'Peak CPU', value: `${text('peakCPU')}%`, time: text('peakCPUTime', ''), color: [0, 173, 239], x: margin + 8 },
    { label: 'Peak Load', value: text('peakLoad'), time: text('peakLoadTime', ''), color: [17, 153, 68], x: margin + colW + 8 },
    { label: 'Peak Memory', value: `${text('peakMemory')}%`, time: text('peakMemoryTime', ''), color: [241, 145, 46], x: margin + (colW * 2) + 8 }
  ].forEach((metric) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(metric.color[0], metric.color[1], metric.color[2]);
    doc.text(metric.label, metric.x, 139);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(metric.value, metric.x, 147);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(metric.time, metric.x, 152);
  });

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Report generated: ${reportDate}`, margin, 170);
  doc.text(`Data range: ${dateInfo}`, margin, 177);
  addFooter(doc, pageWidth, pageHeight, margin, hostname, 1);

  const sections: ChartSection[] = [
    { button: '#btnCPUs', name: 'CPU Utilization', afterClick: () => { click('#btnCPUs'); window.setTimeout(() => click('#nav ul#ulCPU>li:first-child>a'), 100); } },
    { button: '#btnMem', name: 'Memory Usage', subButton: '#btnMemUsg' },
    { button: '#btnMem', name: 'Memory Free', subButton: '#btnMemFree' },
    { button: '#btnIO', name: 'I/O Activity' },
    { button: '#btnLoad', name: 'System Load' },
    { button: '#btnProcesses', name: 'Processes', subButton: '#btnProcs' },
    { button: '#btnSwap', name: 'Swapping', subButton: '#btnSwap' },
    { button: '#btnDevices', name: 'Block Devices' },
    { button: '#btnInterfaceTraffics', name: 'Interface Traffic' },
    { button: '#btnInterfaceErrors', name: 'Interface Errors' },
    { button: '#btnSockets', name: 'Sockets' }
  ];

  window.show?.('#spinner');
  window.updateProgress?.(0, 'Generating PDF...');
  let pageNum = 1;

  for (let index = 0; index < sections.length; index += 1) {
    const section = sections[index];
    const progress = Math.round((index / sections.length) * 100);
    window.updateProgress?.(progress, `Exporting ${section.name}... ${progress}%`);
    await renderSection(section);
    const images = await captureVisibleCharts();
    if (!images.length) continue;

    doc.addPage('landscape');
    pageNum += 1;
    doc.setFillColor(35, 47, 62);
    doc.rect(0, 0, pageWidth, 18, 'F');
    doc.setFillColor(255, 153, 0);
    doc.rect(0, 18, pageWidth, 1.5, 'F');
    doc.setTextColor(255, 153, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(section.name, margin, 12);
    doc.setTextColor(200, 200, 200);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(hostname, pageWidth - margin - 40, 12);

    const chartY = 24;
    const chartHeight = images.length <= 2
      ? (pageHeight - chartY - 20) / images.length - 5
      : (pageHeight - chartY - 20) / Math.ceil(images.length / 2) - 5;

    images.forEach((image, imageIndex) => {
      if (images.length <= 2) {
        doc.addImage(image, 'PNG', margin, chartY + imageIndex * (chartHeight + 5), contentWidth, chartHeight);
        return;
      }
      const col = imageIndex % 2;
      const row = Math.floor(imageIndex / 2);
      doc.addImage(
        image,
        'PNG',
        margin + col * (contentWidth / 2 + 2),
        chartY + row * (chartHeight + 5),
        contentWidth / 2 - 2,
        chartHeight
      );
    });
    addFooter(doc, pageWidth, pageHeight, margin, hostname, pageNum);
  }

  window.progressBarReset?.();
  doc.save(`SAR_Report_${hostname}_${new Date().toISOString().slice(0, 10)}.pdf`);
  click('#btnSAR');
}

export function PdfExportBridge() {
  useEffect(() => {
    window.sarkartGeneratePDFReport = generatePDFReport;
    return () => {
      if (window.sarkartGeneratePDFReport === generatePDFReport) delete window.sarkartGeneratePDFReport;
    };
  }, []);

  return null;
}
